name: Upload Demo

on:
  push:
    branches:    
      - main
    paths:
      - 'test/**'

jobs:
  upload-demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: demo-model
          path: ${{ github.workspace }}/test/**/*
