name: Documentation

on:
  push:
    branches:    
      - main
    paths:
      - 'test/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: test/
          dest: demo.zip